### ISSUE TITLE
不懂就问, 为什么还需要container层?

### ISSUE THREAD

**Issue by yanghaku** [second-state/tencent-scf-wasm-runtime#2]
WebAssembly自身的优势, 可以提供强内存隔离, 并且对于网络/文件系统也能做到有力的控制, 脱离container之后, wasmEdge单独运行可以大幅提高 serverless 函数的性能，降低 infrastructure 的成本, 但是为什么当前的实现还是要在container里面呢?

**Comment by alabulei1** [comment]
Hi @yanghaku 

Sorry for my late reply. 

是的，你说的没错。WasmEdge 当然是可以不在 container 运行的，独立运行的。之所以这个 repo 还在 container 里，是因为腾讯云 serverless 的架构是基于 container 的，我们不得不这样做。

我们正在做纯 Wasm 的 serverless 平台，欢迎到时来试用。

**Comment by yanghaku** [comment]
好的， 感谢您的回复！
